# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-12 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajax', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testincart',
            old_name='fl',
            new_name='name',
        ),
    ]
