# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='present_day1',
            field=models.BooleanField(default=False),
        ),
    ]
