# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax', '0002_auto_20180112_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='testincart',
            name='session_key',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
